In [1]:
import numpy as np

In [2]:
#simplest way to create an array is to use python list
mypythonlist = [123,345,567]
print(mypythonlist)

[123, 345, 567]


In [4]:
#to convert python list to an array by using the obeject np.array
numpy_array_from_list = np.array(mypythonlist)
numpy_array_from_list

array([123, 345, 567])

In [5]:
a = np.array([1,6,7,5,3])
print(a)

[1 6 7 5 3]


In [6]:
y=numpy_array_from_list +10
print(y)

[133 355 577]


In [7]:
a = np.array([1,2,3,4])
print(a.shape)
print(a.dtype)

(4,)
int32


In [10]:
### different type
b= np.array([1.2,2.3,3.4,5.6])
print(b.dtype)

float64


In [11]:
## 2dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [16]:
# 3 dimension
d = np.array([
    [[1,2,3],
       [4,5,6]],
    [[7,8,9],
       [10,11,12]]
     
])
print(d.shape)
(2,2,3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [21]:
import numpy as np
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [22]:
#reshape data
import numpy as np
e = np.array([(1,2,3),(4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [24]:
#horizontal stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal append:',np.hstack((f,g)))

Horizontal append: [1 2 3 4 5 6]


In [25]:
##vertical stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f,g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [26]:
##generating random numbers
normal_array = np.random.normal(6,0.6,12)
print(normal_array)

[7.00034622 5.84177308 5.82552349 5.38910113 5.11088725 5.40689049
 6.08576132 7.73217577 6.58509652 5.03003331 5.99969871 6.91206849]


In [27]:
A = np.matrix(np.ones((4,4)))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [30]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(1,14,4)

array([ 1,  5,  9, 13])